version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: ls app
          command: ls /Applications/

  build: 
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: 
      - checkout
      - run:
          # build our application
          name: uname
          command: uname -a
          
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
