name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env: 
        DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
      run: |
        make
        swift test
